name: Build and deploy Node.js app to Azure Web App - tungage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js version
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build the project
        run: |
          echo "Starting build process..."
          npm run build --if-present

      # Step 5: Verify the dist directory exists
      - name: Verify dist directory after build
        run: |
          echo "Verifying dist directory..."
          if (Test-Path -Path "./dist") {
            echo "✅ dist directory exists."
          } else {
            echo "❌ Error: dist directory does not exist!"
            exit 1
          }

      # Step 6: List dist directory contents
      - name: List dist directory contents
        run: |
          echo "Contents of dist directory:"
          Get-ChildItem -Recurse ./dist

      # Step 7: Upload artifact for deployment
      - name: Upload dist directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      # Step 1: Download artifact
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./dist # Extract artifact to ./dist folder

      # Step 2: Verify downloaded artifact
      - name: Verify downloaded artifact contents
        run: |
          echo "Listing downloaded artifact contents:"
          ls -la ./dist

      # Step 3: Log in to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E0EA74F50BC94FBF8F5CE2EDF4ECA438 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_72B9CAB6DE9A48A9B3158985C2A549DA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F7BC9BFE3D744153BC4C4F3D17560373 }}

      # Step 4: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "tungage"
          slot-name: "Production"
          package: ./dist

      # Step 5: Verify Deployment
      - name: Verify Deployment
        run: |
          echo "Deployment completed. Verifying..."
          curl -I ${{ steps.deploy-to-webapp.outputs.webapp-url }}
